### ISSUE TITLE
Rephrase README so that it is less discouraging for newbies

### ISSUE THREAD

**Issue by JeremiePat** [JeremiePat/svg1k#3]
Good point raised by @cassieevans : https://twitter.com/cassiecodes/status/1272881499449315329

Any suggestion that help encouraging beginners without being too discouraging about expectation is welcome.

**Comment by JeremiePat** [comment]
Suggested change:

> **Can I submit any SVG like a simple circle?**
>
> We do not have any formal acceptance criteria, we only expect you to push forward the limit of your knowledge of the technology. Regardless about what we subjectively think about your submission we will do our best to provide constructive feedback on your PR to improve your submission in a way it will be awesome (and we're pretty sure you can do better than a circle 😉).

@cassieevans do you think it's better? Any suggestion to improve this would be awesome and let me know if you've spotted other area where the text is somewhat "yikes".

**Comment by cassieevans** [comment]
That sounds a lot better, I wrote this up too -

**Will all submissions be featured on the site?**

We don't have any formal acceptance criteria, but whatever your knowledge of SVG, we encourage you to push the boundaries and experiment!
We will showcase the submissions we feel best push the limits of the technology. We can't guarantee your contribution will be accepted, but we will do our best to provide constructive feedback on your PR if we see a way to make it even better!

**Comment by JeremiePat** [comment]
I've update the README with something highly inspired by your suggestion. Let me knows if there are other things that can be improved in any ways.
